// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendAPI.Models
{
    public partial class Cungcap
    {
        public int CungcapId { get; set; }
        public string Tendaydu { get; set; }
        public string TenLienhe { get; set; }
        public string Diachi { get; set; }
        public string Thanhpho { get; set; }
        public string MaBuudien { get; set; }
        public string Quocgia { get; set; }
        public string Dienthoai { get; set; }
    }
}