// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendAPI.Models
{
    public partial class Danhmuc
    {
        public int DanhmucId { get; set; }
        public string TenDanhMuc { get; set; }
        public string MoTa { get; set; }
    }
}