// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendAPI.Models
{
    public partial class DonhangChitiet
    {
        public int DonhangChitietId { get; set; }
        public int? DonhangId { get; set; }
        public int? SanphamId { get; set; }
        public int? Soluong { get; set; }
    }
}