// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendAPI.Models
{
    public partial class Donhang
    {
        public int DonhangId { get; set; }
        public int? KhachhangId { get; set; }
        public int? NhanvienId { get; set; }
        public DateTime? Ngaydathang { get; set; }
        public int? ShipperId { get; set; }
    }
}