// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendAPI.Models
{
    public partial class Khachhang
    {
        public int KhachhangId { get; set; }
        public string HoTen { get; set; }
        public string TenLienLac { get; set; }
        public string Diachi { get; set; }
        public string Thanhpho { get; set; }
        public string MaBuudien { get; set; }
        public string QuocGia { get; set; }
    }
}