// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendAPI.Models
{
    public partial class Nhanvien
    {
        public int NhanviennId { get; set; }
        public string Ten { get; set; }
        public string Ho { get; set; }
        public DateTime? NgaySinh { get; set; }
        public string Anh { get; set; }
        public string Ghichu { get; set; }
    }
}