// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendAPI.Models
{
    public partial class Shipper
    {
        public int ShipperId { get; set; }
        public string Hoten { get; set; }
        public string Sodienthoai { get; set; }
    }
}